(cl:defpackage planner-srv
  (:use )
  (:export
   "ADDROBOTMESSAGE"
   "<ADDROBOTMESSAGE-REQUEST>"
   "ADDROBOTMESSAGE-REQUEST"
   "<ADDROBOTMESSAGE-RESPONSE>"
   "ADDROBOTMESSAGE-RESPONSE"
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
  ))

