// Generated by gencpp from file planner/AddRobotMessageResponse.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_ADDROBOTMESSAGERESPONSE_H
#define PLANNER_MESSAGE_ADDROBOTMESSAGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner
{
template <class ContainerAllocator>
struct AddRobotMessageResponse_
{
  typedef AddRobotMessageResponse_<ContainerAllocator> Type;

  AddRobotMessageResponse_()
    : response()  {
    }
  AddRobotMessageResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::planner::AddRobotMessageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner::AddRobotMessageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddRobotMessageResponse_

typedef ::planner::AddRobotMessageResponse_<std::allocator<void> > AddRobotMessageResponse;

typedef boost::shared_ptr< ::planner::AddRobotMessageResponse > AddRobotMessageResponsePtr;
typedef boost::shared_ptr< ::planner::AddRobotMessageResponse const> AddRobotMessageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner::AddRobotMessageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner::AddRobotMessageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner::AddRobotMessageResponse_<ContainerAllocator1> & lhs, const ::planner::AddRobotMessageResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner::AddRobotMessageResponse_<ContainerAllocator1> & lhs, const ::planner::AddRobotMessageResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::planner::AddRobotMessageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::AddRobotMessageResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::AddRobotMessageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::AddRobotMessageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::AddRobotMessageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::AddRobotMessageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner::AddRobotMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::planner::AddRobotMessageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::planner::AddRobotMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner/AddRobotMessageResponse";
  }

  static const char* value(const ::planner::AddRobotMessageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner::AddRobotMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
"\n"
;
  }

  static const char* value(const ::planner::AddRobotMessageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner::AddRobotMessageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddRobotMessageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner::AddRobotMessageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner::AddRobotMessageResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MESSAGE_ADDROBOTMESSAGERESPONSE_H
