// Generated by gencpp from file planner/AddRobotMessageRequest.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_ADDROBOTMESSAGEREQUEST_H
#define PLANNER_MESSAGE_ADDROBOTMESSAGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner
{
template <class ContainerAllocator>
struct AddRobotMessageRequest_
{
  typedef AddRobotMessageRequest_<ContainerAllocator> Type;

  AddRobotMessageRequest_()
    : request()  {
    }
  AddRobotMessageRequest_(const ContainerAllocator& _alloc)
    : request(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::planner::AddRobotMessageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner::AddRobotMessageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddRobotMessageRequest_

typedef ::planner::AddRobotMessageRequest_<std::allocator<void> > AddRobotMessageRequest;

typedef boost::shared_ptr< ::planner::AddRobotMessageRequest > AddRobotMessageRequestPtr;
typedef boost::shared_ptr< ::planner::AddRobotMessageRequest const> AddRobotMessageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner::AddRobotMessageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner::AddRobotMessageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planner::AddRobotMessageRequest_<ContainerAllocator1> & lhs, const ::planner::AddRobotMessageRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planner::AddRobotMessageRequest_<ContainerAllocator1> & lhs, const ::planner::AddRobotMessageRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::planner::AddRobotMessageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::AddRobotMessageRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::AddRobotMessageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::AddRobotMessageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::AddRobotMessageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::AddRobotMessageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner::AddRobotMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b13f31f7a0a36901919f7ec0d9f40d4";
  }

  static const char* value(const ::planner::AddRobotMessageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b13f31f7a0a3690ULL;
  static const uint64_t static_value2 = 0x1919f7ec0d9f40d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner::AddRobotMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner/AddRobotMessageRequest";
  }

  static const char* value(const ::planner::AddRobotMessageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner::AddRobotMessageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string request\n"
;
  }

  static const char* value(const ::planner::AddRobotMessageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner::AddRobotMessageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddRobotMessageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner::AddRobotMessageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner::AddRobotMessageRequest_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MESSAGE_ADDROBOTMESSAGEREQUEST_H
